export const ADD_FORM = 'FORMS:ADD_FORM';
export const REGISTER_INPUT = 'FORMS:REGISTER_INPUT';
export const UNREGISTER_INPUT = 'FORMS:UNREGISTER_INPUT';
export const CHANGE_INPUT = 'FORMS:CHANGE_INPUT';
export const EXTERNAL_CHANGE_INPUT = 'FORMS:EXTERNAL_CHANGE_INPUT';
export const UPDATE_FORM = 'FORMS:UPDATE_FORM';
export const REMOVE_FORM = 'FORMS:REMOVE_FORM';
