/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		'./index.html',
		'./main/**/*.{jsx,js,ts,jsx,tsx}',
		'./admin/**/*.{jsx,js,ts,jsx,tsx}',
	],
	theme: {
		container: {
			padding: '20px',
			screens: {
				'2xl': '1312px',
			},
		},
		extend: {
			colors: {
				'burnt-sienna': 'var(--burnt-sienna)',
				platinum: 'var(--platinum)',
				'primitive-color-brand-black': 'var(--primitive-color-brand-black)',
				'primitive-color-brand-white': 'var(--primitive-color-brand-white)',
				'primitive-color-neutral-neutral-darker':
					'var(--primitive-color-neutral-neutral-darker)',
				'primitive-color-neutral-neutral-darkest':
					'var(--primitive-color-neutral-neutral-darkest)',
				'primitive-color-neutral-neutral-lighter':
					'var(--primitive-color-neutral-neutral-lighter)',
				'raisin-black': 'var(--raisin-black)',
				'semantic-background-color-error':
					'var(--semantic-background-color-error)',
				'semantic-background-color-secondary':
					'var(--semantic-background-color-secondary)',
				'semantic-background-color-success':
					'var(--semantic-background-color-success)',
				'semantic-background-color-tertiary':
					'var(--semantic-background-color-tertiary)',
				'semantic-link-alternate': 'var(--semantic-link-alternate)',
				'semantic-link-primary': 'var(--semantic-link-primary)',
				'semantic-link-secondary': 'var(--semantic-link-secondary)',
				'semantic-text-error': 'var(--semantic-text-error)',
				'semantic-text-secondary': 'var(--semantic-text-secondary)',
				'semantic-text-success': 'var(--semantic-text-success)',
				silver: 'var(--silver)',
				white: 'var(--white)',
			},
			fontFamily: {
				sans: ['Lexend', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				'heading-desktop-h1': 'var(--heading-desktop-h1-font-family)',
				'heading-desktop-h2': 'var(--heading-desktop-h2-font-family)',
				'heading-desktop-h3': 'var(--heading-desktop-h3-font-family)',
				'heading-desktop-h4': 'var(--heading-desktop-h4-font-family)',
				'heading-desktop-h5': 'var(--heading-desktop-h5-font-family)',
				'heading-desktop-h6': 'var(--heading-desktop-h6-font-family)',
				'heading-mobile-h1': 'var(--heading-mobile-h1-font-family)',
				'heading-mobile-h2': 'var(--heading-mobile-h2-font-family)',
				'heading-mobile-h3': 'var(--heading-mobile-h3-font-family)',
				'heading-mobile-h4': 'var(--heading-mobile-h4-font-family)',
				'heading-mobile-h5': 'var(--heading-mobile-h5-font-family)',
				'heading-mobile-h6': 'var(--heading-mobile-h6-font-family)',
				'text-large-bold': 'var(--text-large-bold-font-family)',
				'text-large-extra-bold': 'var(--text-large-extra-bold-font-family)',
				'text-large-light': 'var(--text-large-light-font-family)',
				'text-large-link': 'var(--text-large-link-font-family)',
				'text-large-medium': 'var(--text-large-medium-font-family)',
				'text-large-normal': 'var(--text-large-normal-font-family)',
				'text-large-semi-bold': 'var(--text-large-semi-bold-font-family)',
				'text-medium-bold': 'var(--text-medium-bold-font-family)',
				'text-medium-extra-bold': 'var(--text-medium-extra-bold-font-family)',
				'text-medium-light': 'var(--text-medium-light-font-family)',
				'text-medium-link': 'var(--text-medium-link-font-family)',
				'text-medium-medium': 'var(--text-medium-medium-font-family)',
				'text-medium-normal': 'var(--text-medium-normal-font-family)',
				'text-medium-semi-bold': 'var(--text-medium-semi-bold-font-family)',
				'text-regular-bold': 'var(--text-regular-bold-font-family)',
				'text-regular-extra-bold': 'var(--text-regular-extra-bold-font-family)',
				'text-regular-light': 'var(--text-regular-light-font-family)',
				'text-regular-link': 'var(--text-regular-link-font-family)',
				'text-regular-medium': 'var(--text-regular-medium-font-family)',
				'text-regular-normal': 'var(--text-regular-normal-font-family)',
				'text-regular-semi-bold': 'var(--text-regular-semi-bold-font-family)',
				'text-small-bold': 'var(--text-small-bold-font-family)',
				'text-small-extra-bold': 'var(--text-small-extra-bold-font-family)',
				'text-small-light': 'var(--text-small-light-font-family)',
				'text-small-link': 'var(--text-small-link-font-family)',
				'text-small-medium': 'var(--text-small-medium-font-family)',
				'text-small-normal': 'var(--text-small-normal-font-family)',
				'text-small-semi-bold': 'var(--text-small-semi-bold-font-family)',
				'text-tiny-bold': 'var(--text-tiny-bold-font-family)',
				'text-tiny-extra-bold': 'var(--text-tiny-extra-bold-font-family)',
				'text-tiny-light': 'var(--text-tiny-light-font-family)',
				'text-tiny-link': 'var(--text-tiny-link-font-family)',
				'text-tiny-medium': 'var(--text-tiny-medium-font-family)',
				'text-tiny-normal': 'var(--text-tiny-normal-font-family)',
				'text-tiny-semi-bold': 'var(--text-tiny-semi-bold-font-family)',
			},
			boxShadow: {
				large: 'var(--large)',
				medium: 'var(--medium)',
				small: 'var(--small)',
				xlarge: 'var(--xlarge)',
				xsmall: 'var(--xsmall)',
				xxlarge: 'var(--xxlarge)',
				xxsmall: 'var(--xxsmall)',
			},
		},
	},
	plugins: [],
};
